version: "3"
services:
  db:
    container_name: app-210408-db
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app-210408
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - "./db-data:/var/lib/mysql"
  pma:
    container_name: app-210408-pma
    image: "phpmyadmin/phpmyadmin:5.1"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
